config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'home_page#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'admin/index'
  get 'sessions/new'  
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home_page/logout'  
  get 'uvl_hobby/index'
  get 'pop_hobby/index'
  get 'pop_hobby/search'

  get 'uvl_hobby/search'
  resources :hobby_sotrs
  resources :sotrs
  resources :hobbies
  get 'home_page/index'
  root 'home_page#index'
  resources :dlzhs
  
end

app/models/dlzh.rb
class Dlzh < ActiveRecord::Base
	has_many :sotrs
end

app/controllers/dlzhs_controller.rb
class DlzhsController < ApplicationController
  before_action :set_dlzh, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]
  
  # GET /dlzhs
  # GET /dlzhs.json
  def index
    @dlzhs = Dlzh.all
  end

  # GET /dlzhs/1
  # GET /dlzhs/1.json
  def show
  end

  # GET /dlzhs/new
  def new
    @dlzh = Dlzh.new
  end

  # GET /dlzhs/1/edit
  def edit
  end

  # POST /dlzhs
  # POST /dlzhs.json
  def create
    @dlzh = Dlzh.new(dlzh_params)

    respond_to do |format|
      if @dlzh.save
        format.html { redirect_to @dlzh, notice: 'Dlzh was successfully created.' }
        format.json { render :show, status: :created, location: @dlzh }
      else
        format.html { render :new }
        format.json { render json: @dlzh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dlzhs/1
  # PATCH/PUT /dlzhs/1.json
  def update
      respond_to do |format|
        if @dlzh.update(dlzh_params)
          format.html { redirect_to @dlzh, notice: 'Dlzh was successfully updated.' }
          format.json { render :show, status: :ok, location: @dlzh }
        else
          format.html { render :edit }
          format.json { render json: @dlzh.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /dlzhs/1
  # DELETE /dlzhs/1.json
  def destroy
      @dlzh.destroy
        respond_to do |format|
          format.html { redirect_to dlzhs_url, notice: 'Dlzh was successfully destroyed.' }
          format.json { head :no_content }
        end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dlzh
      @dlzh = Dlzh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dlzh_params
      params.require(:dlzh).permit(:d_name, :status, :s_delete)
    end
end

app/helpers/dlzhs_helper.rb
module DlzhsHelper
end

app/views/dlzhs/_form.html.erb
<%= form_for(@dlzh) do |f| %>
  <% if @dlzh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dlzh.errors.count, "error") %> Произошла ошибка, должностей не записана:</h2>

      <ul>
      <% @dlzh.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Название_дожности %><br>
    <%= f.text_field :d_name %>
  </div>
  <div class="field">
    <%= f.label :Статус %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :Удаление %><br>
    <%= f.check_box :s_delete %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить должность" %>
  </div>
<% end %>

app/views/dlzhs/edit.html.erb
<h1>Редактирование должности</h1>

<% if @dlzh.status==true %>
	<p><font color="Red" size="48"><%= flash[:notice] = "Запись находится в состоянии редактирования!" %></font></p>
<% end %>

<%= render 'form' %>

<%= link_to 'Показать', @dlzh %> |
<%= link_to 'Назад', dlzhs_path %>

app/views/dlzhs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Справочник должностей</h1>


<%= link_to 'Новая должность', new_dlzh_path %> |
<%= link_to 'Главная страница', controller: 'home_page' %>

<table>
  <thead>
    <tr>
      <th>Название должности</th>
      <th>Статус</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dlzhs.each do |dlzh| %>
      <% if dlzh.s_delete == false %>
        <tr>
      <% else %>
        <tr bgcolor="Red">
      <% end %>
          <td><%= dlzh.d_name %></td>
          <td><%= dlzh.status %></td>
          <td><%= link_to 'Показать', dlzh %></td>
          <td><%= link_to 'Изменить', edit_dlzh_path(dlzh) %></td>
          <% if session[:user_id] == 2 %>
            <td><%= link_to 'Удалить', dlzh, method: :delete, data: { confirm: 'Вы уверены?' } %></td>  
          <% end %>
        </tr >
    <% end %> 
  </tbody>
</table>

app/views/dlzhs/new.html.erb
<h1>Новая должность</h1>

<%= render 'form' %>

<%= link_to 'Назад', dlzhs_path %>

app/views/dlzhs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название должности:</strong>
  <%= @dlzh.d_name %>
</p>

<%= link_to 'Изменить', edit_dlzh_path(@dlzh) %> |
<%= link_to 'Назад', dlzhs_path %>