config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'home_page#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'admin/index'
  get 'sessions/new'  
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home_page/logout'  
  get 'uvl_hobby/index'
  get 'pop_hobby/index'
  get 'pop_hobby/search'

  get 'uvl_hobby/search'
  resources :hobby_sotrs
  resources :sotrs
  resources :hobbies
  get 'home_page/index'
  root 'home_page#index'
  resources :dlzhs
  
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
	has_many :hobby_sotrs
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1
  # GET /hobbies/1.json
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to @hobby, notice: 'Hobby was successfully created.' }
        format.json { render :show, status: :created, location: @hobby }
      else
        format.html { render :new }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to @hobby, notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
      params.require(:hobby).permit(:h_name, :status, :s_delete)
    end
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/_form.html.erb
<%= form_for(@hobby) do |f| %>
  <% if @hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hobby.errors.count, "error") %> Произошла ошибка, должностей не записана:</h2>

      <ul>
      <% @hobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Название_хобби %><br>
    <%= f.text_field :h_name %>
  </div>
  <div class="field">
    <%= f.label :Статус %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :Удаление %><br>
    <%= f.check_box :s_delete %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить хобби" %>
  </div>
<% end %>

app/views/hobbies/edit.html.erb
<h1>Редактирование хобби</h1>

<% if @hobby.status==true %>
	<p><font color="Red" size="48"><%= flash[:notice] = "Запись находится в состоянии редактирования!" %></font></p>
<% end %>

<%= render 'form' %>

<%= link_to 'Показать', @hobby %> |
<%= link_to 'Назад', hobbies_path %>

app/views/hobbies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Справочник хобби</h1>

<%= link_to 'Новое хобби', new_hobby_path %> |
<%= link_to 'Главная страница', controller: 'home_page' %>


<table>
  <thead>
    <tr>
      <th>Название хобби</th>
      <th>Статус</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hobbies.each do |hobby| %>
      <% if hobby.s_delete == false %>
        <tr>
      <% else %>
        <tr bgcolor="Red">
      <% end %>
        <td><%= hobby.h_name %></td>
        <td><%= hobby.status %></td>
        <td><%= link_to 'Показать', hobby %></td>
        <td><%= link_to 'Изменить', edit_hobby_path(hobby) %></td>
        <% if session[:user_id] == 2 %>
          <td><%= link_to 'Удалить', hobby, method: :delete, data: { confirm: 'Вы уверены?' } %></td>  
        <% end %>
      </tr>      
    <% end %>
  </tbody>
</table>

<br>

app/views/hobbies/new.html.erb
<h1>Новое хобби</h1>

<%= render 'form' %>

<%= link_to 'Назад', hobbies_path %>

app/views/hobbies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название хобби:</strong>
  <%= @hobby.h_name %>
</p>

<%= link_to 'Изменить', edit_hobby_path(@hobby) %> |
<%= link_to 'Назад', hobbies_path %>