config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'home_page#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'admin/index'
  get 'sessions/new'  
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'home_page/logout'  
  get 'uvl_hobby/index'
  get 'pop_hobby/index'
  get 'pop_hobby/search'

  get 'uvl_hobby/search'
  resources :hobby_sotrs
  resources :sotrs
  resources :hobbies
  get 'home_page/index'
  root 'home_page#index'
  resources :dlzhs
  
end

app/models/sotr.rb
class Sotr < ActiveRecord::Base
  belongs_to :dlzh
  has_many :hobby_sotrs
end

app/controllers/sotrs_controller.rb
class SotrsController < ApplicationController
  before_action :set_sotr, only: [:show, :edit, :update, :destroy]

  # GET /sotrs
  # GET /sotrs.json
  def index
    @sotrs = Sotr.all
  end

  # GET /sotrs/1
  # GET /sotrs/1.json
  def show
  end

  # GET /sotrs/new
  def new
    @sotr = Sotr.new
  end

  # GET /sotrs/1/edit
  def edit
  end

  # POST /sotrs
  # POST /sotrs.json
  def create
    @sotr = Sotr.new(sotr_params)

    respond_to do |format|
      if @sotr.save
        format.html { redirect_to @sotr, notice: 'Sotr was successfully created.' }
        format.json { render :show, status: :created, location: @sotr }
      else
        format.html { render :new }
        format.json { render json: @sotr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sotrs/1
  # PATCH/PUT /sotrs/1.json
  def update
    respond_to do |format|
      if @sotr.update(sotr_params)
        format.html { redirect_to @sotr, notice: 'Sotr was successfully updated.' }
        format.json { render :show, status: :ok, location: @sotr }
      else
        format.html { render :edit }
        format.json { render json: @sotr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sotrs/1
  # DELETE /sotrs/1.json
  def destroy
    @sotr.destroy
    respond_to do |format|
      format.html { redirect_to sotrs_url, notice: 'Sotr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sotr
      @sotr = Sotr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sotr_params
      params.require(:sotr).permit(:s_fam, :s_name, :s_otch, :s_date, :dlzh_id, :s_photo, :status, :s_delete)
    end
end

app/helpers/sotrs_helper.rb
module SotrsHelper
end

app/views/sotrs/_form.html.erb
<%= form_for(@sotr) do |f| %>
  <% if @sotr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sotr.errors.count, "error") %> Произошла ошибка, должностей не записана:</h2>

      <ul>
      <% @sotr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Фамилия %><br>
    <%= f.text_field :s_fam %>
  </div>
  <div class="field">
    <%= f.label :Имя %><br>
    <%= f.text_field :s_name %>
  </div>
  <div class="field">
    <%= f.label :Отчество %><br>
    <%= f.text_field :s_otch %>
  </div>
  <div class="field">
    <%= f.label :Дата_рождения %><br>
    <%= f.date_select :s_date, start_year: 1930, end_year: 1998 %>
  </div>
  <div class="field">
    <%= f.label :Должность %><br>
    <%= f.collection_select(:dlzh_id, Dlzh.all, :id, :d_name) %>
  </div>
  <div class="field">
    <%= f.label :Фото %><br>
    <%= f.text_field :s_photo %>
  </div>
  <div class="field">
    <%= f.label :Статус %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :Удаление %><br>
    <%= f.check_box :s_delete %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить сотрудника" %>
  </div>
<% end %>

app/views/sotrs/edit.html.erb
<h1>Редактирование сотрудника</h1>

<% if @sotr.status==true %>
	<p><font color="Red" size="48"><%= flash[:notice] = "Запись находится в состоянии редактирования!" %></font></p>
<% end %>

<%= render 'form' %>

<%= link_to 'Изменить', @sotr %> |
<%= link_to 'Назад', sotrs_path %>

app/views/sotrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Справочник сотрудники</h1>

<%= link_to 'Новый сотрудник', new_sotr_path %> |
<%= link_to 'Главная страница', controller: 'home_page' %>

<table>
  <thead>
    <tr>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отчество</th>
      <th>дата рождения</th>
      <th>Должность</th>
      <th>Фотография</th>
      <th>Статус</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sotrs.each do |sotr| %>
      <% if sotr.s_delete == false %>
        <tr>
      <% else %>
        <tr bgcolor="Red">
      <% end %>
        <td><%= sotr.s_fam %></td>
        <td><%= sotr.s_name %></td>
        <td><%= sotr.s_otch %></td>
        <td><%= sotr.s_date %></td>
        <td><%= sotr.dlzh.d_name %></td>
        <td><%= sotr.s_photo %></td>
        <td><%= sotr.status %></td>
        <td><%= link_to 'Показать', sotr %></td>
        <td><%= link_to 'Изменить', edit_sotr_path(sotr) %></td>
        <% if session[:user_id] == 2 %>
          <td><%= link_to 'Удалить', sotr, method: :delete, data: { confirm: 'Вы уверены?' } %></td>  
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sotrs/new.html.erb
<h1>Новый сотрудник</h1>

<%= render 'form' %>

<%= link_to 'Назад', sotrs_path %>

app/views/sotrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Фамилия:</strong>
  <%= @sotr.s_fam %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @sotr.s_name %>
</p>

<p>
  <strong>Отчество:</strong>
  <%= @sotr.s_otch %>
</p>

<p>
  <strong>Дата рождения:</strong>
  <%= @sotr.s_date %>
</p>

<p>
  <strong>Должность:</strong>
  <%= @sotr.dlzh.d_name %>
</p>

<p>
  <strong>Фотография:</strong>
  <%= @sotr.s_photo %>
</p>

<%= link_to 'Изменить', edit_sotr_path(@sotr) %> |
<%= link_to 'Назад', sotrs_path %>